param()

$ErrorActionPreference = 'Stop'

$repoRoot = Resolve-Path (Join-Path $PSScriptRoot '..')
$loaders = @('paper', 'forge', 'fabric', 'neoforge', 'sponge')
$matrixFiles = @(
    'versions/minecraft-1.8-1.12-builds.json',
    'versions/minecraft-1.13-1.16-builds.json',
    'versions/minecraft-1.17-1.20-builds.json',
    'versions/minecraft-1.21x-builds.json'
)

$byVersion = @{}

foreach ($relativeFile in $matrixFiles) {
    $fullPath = Join-Path $repoRoot $relativeFile
    if (-not (Test-Path $fullPath)) {
        throw "Missing matrix file: $relativeFile"
    }

    $json = Get-Content $fullPath -Raw | ConvertFrom-Json
    foreach ($entry in @($json.versions)) {
        $mc = [string]$entry.mc
        if ([string]::IsNullOrWhiteSpace($mc)) {
            continue
        }

        $byVersion[$mc] = [ordered]@{
            mc = $mc
            source_matrix = $relativeFile
            paper_api_version = [string]$entry.paper_api_version
            sponge_api_version = [string]$entry.sponge_api_version
            fabric_loader_version = [string]$entry.fabric_loader_version
            fabric_api_version = [string]$entry.fabric_api_version
            yarn_mappings = [string]$entry.yarn_mappings
            forge_version = [string]$entry.forge_version
            neoforge_version = [string]$entry.neoforge_version
        }
    }
}

$sortedVersions = @(
    $byVersion.Keys |
    Sort-Object {
        $parts = (($_ -replace '[^0-9.]', '').Split('.') | Where-Object { $_ -ne '' })
        $major = if ($parts.Length -gt 0) { [int]$parts[0] } else { 0 }
        $minor = if ($parts.Length -gt 1) { [int]$parts[1] } else { 0 }
        $patch = if ($parts.Length -gt 2) { [int]$parts[2] } else { 0 }
        '{0:D3}.{1:D3}.{2:D3}' -f $major, $minor, $patch
    }
)

$createdRoots = @{}
$createdCount = 0

foreach ($loader in $loaders) {
    $loaderRoot = Join-Path $repoRoot $loader
    New-Item -ItemType Directory -Force -Path $loaderRoot | Out-Null

    foreach ($mc in $sortedVersions) {
        $data = $byVersion[$mc]
        $dir = Join-Path $loaderRoot $mc
        $srcJava = Join-Path $dir 'src/main/java'
        $srcRes = Join-Path $dir 'src/main/resources'

        New-Item -ItemType Directory -Force -Path $srcJava | Out-Null
        New-Item -ItemType Directory -Force -Path $srcRes | Out-Null

        $moduleName = "nekonametags-$loader-$mc"
        $buildGradle = @"
plugins {
    java
}

group = "uk.co.nekosunevr"
version = rootProject.findProperty("mod_version")?.toString() ?: "0.0.0-dev"

base {
    archivesName.set("$moduleName")
}

java {
    withSourcesJar()
}

// Generated scaffold from matrix files.
// Fill this module with loader/version-specific implementation.
"@
        Set-Content -Path (Join-Path $dir 'build.gradle.kts') -Value $buildGradle -Encoding ASCII

        $readme = @"
# $loader $mc

Generated from: $($data.source_matrix)

Matrix values:
- mc: $($data.mc)
- paper_api_version: $($data.paper_api_version)
- sponge_api_version: $($data.sponge_api_version)
- fabric_loader_version: $($data.fabric_loader_version)
- fabric_api_version: $($data.fabric_api_version)
- yarn_mappings: $($data.yarn_mappings)
- forge_version: $($data.forge_version)
- neoforge_version: $($data.neoforge_version)

This folder follows the same module-style layout (build.gradle.kts, src/main/java, src/main/resources).
"@
        Set-Content -Path (Join-Path $dir 'README.md') -Value $readme -Encoding ASCII

        $metadata = $data | ConvertTo-Json -Depth 4
        Set-Content -Path (Join-Path $dir 'matrix.json') -Value $metadata -Encoding ASCII

        Set-Content -Path (Join-Path $srcJava '.gitkeep') -Value '' -Encoding ASCII
        Set-Content -Path (Join-Path $srcRes '.gitkeep') -Value '' -Encoding ASCII

        $createdCount++
    }

    $createdRoots[$loader] = $sortedVersions.Count
}

$index = @()
$index += '# Loader/Version Folder Index'
$index += ''
$index += 'Generated by `tools/generate-loader-version-folders.ps1` from:'
foreach ($file in $matrixFiles) {
    $index += "- $file"
}
$index += ''
$index += 'Folders created:'
foreach ($loader in $loaders) {
    $index += "- ${loader}: $($createdRoots[$loader]) versions"
}
$index += ''
$index += "Total module folders: $createdCount"
Set-Content -Path (Join-Path $repoRoot 'versions/loader-version-folders.md') -Value ($index -join "`r`n") -Encoding ASCII

Write-Host "Created $createdCount loader/version module folders."
